package interfaz;

import java.io.File;
import java.io.FileOutputStream;
import java.io.FileNotFoundException;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego Rivera
 */
public class VentanaPDF extends javax.swing.JFrame {

    /**
     * Creates new form PDf
     */
    public VentanaPDF() {
        initComponents();
        this.setTitle("GENERAR EL PDF");
        this.getContentPane().setBackground(Color.white);
        this.jLabel1.setForeground(Color.black);
        this.jLabel2.setForeground(Color.black);
        this.jLabel3.setForeground(Color.black);
        this.jLabel4.setForeground(Color.black);
        this.jLabel5.setForeground(Color.black);
        this.Generar.setBackground(Color.black);
        this.Generar.setForeground(Color.white);
        Generar.setFont(new java.awt.Font("Agency FB", java.awt.Font.ITALIC, 20));
        this.Firmar.setBackground(Color.black);
        this.Firmar.setForeground(Color.white);
        Firmar.setFont(new java.awt.Font("Agency FB", java.awt.Font.ITALIC, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JTextField();
        Apellidos = new javax.swing.JTextField();
        Boleta = new javax.swing.JTextField();
        Firmar = new javax.swing.JButton();
        Generar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mensaje = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(500, 250, 0, 0));

        Firmar.setText("Menu principal");
        Firmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirmarActionPerformed(evt);
            }
        });

        Generar.setText("Generar");
        Generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        jLabel3.setText("Edad");

        jLabel4.setText("Razones por las que me deberia de pasar:");

        Mensaje.setColumns(20);
        Mensaje.setRows(5);
        jScrollPane1.setViewportView(Mensaje);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Generar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(Firmar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Boleta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Generar)
                    .addComponent(Firmar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirmarActionPerformed
        // TODO add your handling code here:
        Inicio Firmita = new Inicio();
        Firmita.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FirmarActionPerformed

    private void GenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarActionPerformed
        try {
            // TODO add your handling code here:
            generar(Nombre.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanaPDF.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(VentanaPDF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GenerarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellidos;
    private javax.swing.JTextField Boleta;
    private javax.swing.JButton Firmar;
    private javax.swing.JButton Generar;
    private javax.swing.JTextArea Mensaje;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void generar(String nombre) throws FileNotFoundException, DocumentException {
        if (!(Nombre.getText().isEmpty() || (Apellidos.getText().isEmpty()) || (Boleta.getText().isEmpty()) || (Mensaje.getText().isEmpty()))) {

            FileOutputStream archivo = new FileOutputStream(nombre + ".pdf");
            Document documento = new Document();
            PdfWriter.getInstance(documento, archivo);

            documento.open();
            Paragraph parrafo = new Paragraph("DATOS OBTENIDOS");
            parrafo.setAlignment(1);

            documento.add(parrafo);
            documento.add(new Paragraph("Nombre: " + Nombre.getText()));
            documento.add(new Paragraph("Apellidos: " + Apellidos.getText()));
            documento.add(new Paragraph("Boleta: " + Boleta.getText()));
            documento.add(new Paragraph("razones: " + Mensaje.getText()));

            documento.close();

            FileOutputStream archivo2 = new FileOutputStream(nombre + "Firmado" + ".pdf");
            Document documento2 = new Document();
            PdfWriter.getInstance(documento2, archivo2);

            documento2.open();
            Paragraph parrafo3 = new Paragraph("Datos personales");
            parrafo.setAlignment(1);

            Paragraph parrafo2 = new Paragraph("avF5w+GA7aM3kRZayoGd+VEauaIj7FkJ1MpZixoIWANxhgswC0UbROthCAQwg9EAdEUyBncy8rVo"
                    + "FLWkhm9tYJ6YpatDwDv/T7NfSQ2VKPAskkDrgeLCpeiln1+SPUn96eKRDN68+dSFe6kk6HWwkRm3"
                    + "iZ+PSsWGtdmey0KYWhjPu2jbZh5qAlms2G8KEWiSCxEv/2JiyWGUE1Yg1Cr4HDGG8oGOhFJgVg4l"
                    + "8tE6rKD24AVfjRAMBGHdoiagxNCoDb0BrO38SkQbPNaPWYD6ISU3VR2/dxEnirSrjEJL/XNYcasn"
                    + "WCGDCptM6alT+D/QI1dqsWYMWdZ2ozqMrG6mgA==");
            parrafo2.setAlignment(1);
            documento2.add(parrafo3);
            documento2.add(new Paragraph("Nombre: " + Nombre.getText()));
            documento2.add(new Paragraph("Apellidos: " + Apellidos.getText()));
            documento2.add(new Paragraph("Boleta: " + Boleta.getText()));
            documento2.add(new Paragraph("Carta de reyes: " + Mensaje.getText()));
            documento2.add(parrafo2);
            documento2.close();

            JOptionPane.showMessageDialog(null, "SE CREO EL PDF");
        } else {
            JOptionPane.showMessageDialog(null, "ERROR, INGRESE TODOS LOS DATOS SOLICITADOS");
        }

    }
}
